### ISSUE TITLE
Better way to get SDK and Rust libs

### ISSUE THREAD

**Issue by nplus11** [tessel/tessel-rust#1]
Steps 8 & 9 of the "Getting Started" section need to updated in the following manner:
1.  Provide a less Kevin dependent way to get SDK
2.  Have the user build the libraries so that they are up to date, and less Kevin dependent
3.  Be os agnostic (preferred), or have instructions for Mac, Linux, PC

@kevinmehall I would like your input on this, but anyone else is free to comment.

As a side note - I created a [new repo here](https://github.com/tessel/rust-example) demonstrating an example project. Feel free to give feedback there as well.

**Comment by kevinmehall** [comment]
We will need to build and publish the SDK. I would like to get a native Mac build in addition to the Linux build. Since we're using static linking, and Rust programs don't depend on many native libraries, we mostly care about gcc (just to use as a linker). If there are existing builds of GCC targeting mipsel in homebrew or elsewhere, we could use those.

I would also like to look into ways to build Rust `libstd` without bootstrapping the entire compiler, such that users can easily build libstd for the Rust version they have. This is possibly less of an issue after 1.0, but I expect users to still want to use the nightly, and it also means we don't have to publish new builds on Rust's 6-week schedule.
